#!/usr/bin/env python3
"""
Simple script to read a Slab 2.0 .grd file and output Cubit command to create
a NURBS surface.
"""

# The code requires numpy, pathlib, argparse, sys, pickle, meshio,
# and the fault_mesh_tools.faultmeshops package.
import numpy as np

from pathlib import Path
import argparse
import sys
import pickle
import pprint

import meshio

from fault_mesh_tools.faultmeshops import faultmeshops
from fault_mesh_tools.faultmeshio import slab2

# ----------------------------------------------------------------------
def slab2_to_cubit(in_path, in_corner_path, out_cub, out_path, resolution, min_elevation, coordsys_info):
    """
    Function to read a Slab 2.0 .grd file and create a quadrilateral mesh of a specified
    resolution.
    """

    # Read Slab 2.0 file.
    (x_in, y_in, vals_in, x_pos_east, y_pos_north) = faultmeshio.slab2.read_slab2(in_path)

    # Get local coordinate info.
    (cartesian_coordsys_info, slab_points, slab_edge) = faultmeshops.create_slab2_geom(x_in, y_in, vals_in, coordsys_info,
                                                                                       min_elevation=min_elevation)
    # Print coordinate system info.
    pprint.pprint(cartesian_coordsys_info)

    # Read corners, if provided.
    corners = None
    if (read_corners):
        corners = np.loadtxt(in_corner, delimiter=',', dtype=np.float64)

    # Get mesh edges.
    quad_edges = faultmeshops.get_quad_mesh_edges(slab_edge, close_corners=corners, sort_first=sort_first)

    # Create grid in local coordinates.
    (mesh_points, num_horiz_points, num_vert_points) = faultmeshops.create_local_grid_points(points, quad_edges, resolution=resolution)
    mesh_points = mesh_points.reshape(num_vert_points, num_horiz_points, 3)

    # Open journal file and create commands.
    f = open(out_journal, 'w')
    f.write('reset\n')

    # Write u-lines.
    for uline in range(num_vert_points):
        write_cubit_line(f, mesh_points[uline,:,:])

    # Write v-lines.
    for vline in range(num_horiz_points):
        write_cubit_line(f, mesh_points[:,vline,:])

    # Create net surface
    i1 = 1
    i2 = num_vert_points
    i3 = num_vert_points + 1
    i4 = i2 + num_horiz_points
    f.write('create surface net u curve %d to %d v curve %d to %d\n' % (i1, i2, i3, i4))
    f.write('delete curve all\n')
    f.write('export Cubit ' + '"' + str(out_cub) + '" overwrite\n')
    f.close()

    return
    

# ======================================================================
if __name__ == "__main__":

    # Get command-line arguments.
    parser = argparse.ArgumentParser(description='Generate Cubit commands to create NURBS surfaces based on input Slab 2.0 file.')
    parser.add_argument("-i", "--in_file", action="store", dest="in_file", required=True, help="input Slab 2.0 .grd file")
    parser.add_argument("-ic", "--in_corner_file", action="store", dest="in_corner_file", default="corners.txt", help="input corner file")
    parser.add_argument("-oj", "--out_journal", action="store", dest="out_journal", required=True, help="output journal file")
    parser.add_argument("-oc", "--out_cubit", action="store", dest="out_cubit", help="output Cubit file")
    parser.add_argument("-rc", "--read_corners", action="store_true", dest="read_corners", help="read file defining mesh corners")
    parser.add_argument("-nrc", "--no_read_corners", action="store_false", dest="read_corners",
                        help="do not read file defining mesh corners")
    parser.add_argument("-r", "--resolution", action="store", dest="resolution", default=2000.0,
                        help="resolution used to create NURBS surface in meters")
    parser.add_argument("-sf", "--sort_first", action="store", dest="sort_first", default="X",
                        help="first sort direction for finding local edges")
    parser.add_argument("-ct", "--cs_type", action="store", dest="cs_type", default='utm', help="type of projected coordinates")
    parser.add_argument("-co", "--cs_orgin_option", action="store", dest="cs_orgin_option", default='compute_origin',
                        help="whether to compute origin coords (compute_origin), use given origin (use_given_origin) or no origin (no_origin)")
    parser.add_argument("-cox", "--cs_origin_x", action="store", dest="cs_origin_x", default=0.0, help="origin x-coordinate")
    parser.add_argument("-coy", "--cs_origin_y", action="store", dest="cs_origin_y", default=0.0, help="origin y-coordinate")
    parser.add_argument("-cop", "--cs_origin_precision", action="store", dest="cs_origin_precision", default=2,
                        help="precision of computed origin")
    parser.add_argument("-cra", "--cs_rot_angle", action="store", dest="cs_rot_angle", default=0.0, help="rotation angle to apply to coordinates")
    parser.add_argument("-me", "--min_elevation", action="store", dest="min_elevation", default=-70000.0, help="min elevation to use")
    parser.set_default(read_corners=False)

    args = parser.parse_args()

    in_path = Path(args.in_file)
    in_corner_path = Path(args.in_corner_file)
    out_path = Path(args.out_journal)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_cub = args.out_cubit
    read_corners = args.read_corners
    resolution = args.resolution
    sort_first = args.sort_first
    cs_type = args.cs_type
    cs_origin_option = args.cs_origin_option
    cs_origin_x = args.cs_origin_x
    cs_origin_y = args.cs_origin_y
    cs_origin_precision = args.cs_origin_precision
    cs_rot_angle = args.cs_rot_angle
    min_elevation = args.min_elevation

    cs_origin = {"x": cs_origin_x,
                 "y": cs_origin_y}
    if (cs_type == "tmerc"):
        cs_origin = {"longitude": cs_origin_x,
                     "latitude": cs_origin_y}

    coordsys_info = {"coordsys_type": cs_type,
                     "coordsys_origin_option": cs_origin_option,
                     "coordsys_origin": cs_origin,
                     "coordsys_origin_precision": cs_origin_precision,
                     "coordsys_rot_angle": cs_rot_angle}
                     

    slab2_to_cubit(in_path, in_corner_path, out_cub, out_path, resolution, min_elevation, coordsys_info)
    
